// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ7sEVAhtY59Y4XIsi8Ed64_hvtIpGM8o',
    appId: '1:573274398235:web:1a865a60e8d092a88922be',
    messagingSenderId: '573274398235',
    projectId: 'iris-app-2024',
    authDomain: 'iris-app-2024.firebaseapp.com',
    storageBucket: 'iris-app-2024.appspot.com',
    measurementId: 'G-DNW2BTPMPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1G3CY2_nxYhrvYUMyvWgn-KquW7LhhoA',
    appId: '1:573274398235:android:7c4d24962c449fb98922be',
    messagingSenderId: '573274398235',
    projectId: 'iris-app-2024',
    storageBucket: 'iris-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_prwAw9XRkHBZuckSWMKoc9qRBIH9STk',
    appId: '1:573274398235:ios:2a97d06ca30f8a008922be',
    messagingSenderId: '573274398235',
    projectId: 'iris-app-2024',
    storageBucket: 'iris-app-2024.appspot.com',
    iosBundleId: 'com.example.irisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_prwAw9XRkHBZuckSWMKoc9qRBIH9STk',
    appId: '1:573274398235:ios:2a97d06ca30f8a008922be',
    messagingSenderId: '573274398235',
    projectId: 'iris-app-2024',
    storageBucket: 'iris-app-2024.appspot.com',
    iosBundleId: 'com.example.irisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ7sEVAhtY59Y4XIsi8Ed64_hvtIpGM8o',
    appId: '1:573274398235:web:5ad19bd3b78955d58922be',
    messagingSenderId: '573274398235',
    projectId: 'iris-app-2024',
    authDomain: 'iris-app-2024.firebaseapp.com',
    storageBucket: 'iris-app-2024.appspot.com',
    measurementId: 'G-5Q2EV7YLYK',
  );
}
